name: "vim help tag name check"
on: [push, pull_request]
jobs:
  tagname:
    name: Check tag name conflict
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: help tag check
        uses: tsuyoshicho/action-vimhelp-tagname-check@3140c342f2dde6b2402e622e580c92f30ce69a28 # v1.1.3
